[tool.poetry]
name = "volttron-new-agent-template"
version = "0.1"
description = "New VOLTTRON agent template"
authors = ["author <author@company.org>"]
license = "Apache-2.0"
packages = [
    { include = "agentpackage" }
]
homepage = "https://github.com/VOLTTRON/volttron-new-agent-template"
repository = "https://github.com/VOLTTRON/volttron-new-agent-template"

keywords = ["volttron", "agent"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
volttron-client = "^0.3.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
pytest = "^6.2.4"
black = "^21.6b0"
flake8 = "^3.9.2"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/'''
